import json
import shutil
import os

ALL_TRAMITES_PATH = 'src/data/allTramites.json'
BACKUP_PATH = 'src/data/allTramites.json.bak_prof'

# 1. Respaldo de seguridad
shutil.copyfile(ALL_TRAMITES_PATH, BACKUP_PATH)
print(f"Respaldo creado en {BACKUP_PATH}")

with open(ALL_TRAMITES_PATH, 'r', encoding='utf-8') as f:
    data = json.load(f)

# Diccionario maestro de auditoría de IA para los 47 trámites de Profesionales
PROFESIONALES_AUDIT = {
    # =========================================================================
    # 1. ABOGADOS Y NOTARIOS (18 TRÁMITES)
    # =========================================================================
    'profesionales-38': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Timbres Fiscales y Papel Sellado de Protocolo',
        'tema': 'Retiro y Gestión de Especies Fiscales',
        'subtema': 'Acreditación de Procurador en Agencia',
        'tramite': 'Acreditación de procurador o tercero para retiro de especies fiscales',
        'descripcion': 'Autoriza a un procurador o tercero mediante carta notarial y boleta SAT-2000 para retirar papel sellado especial de protocolos o timbres fiscales en agencias tributarias.',
        'baseLegal': 'Decreto 37-92 (Ley del Impuesto de Timbres Fiscales y de Papel Sellado Especial para Protocolos, Arts. 23 al 28).',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Presencial / Agencia',
        'esBrecha': False
    },
    'profesionales-70': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Habilitación y Registro Notarial',
        'tema': 'Registro Tributario Unificado (RTU)',
        'subtema': 'Inscripción y Calidad de Notario',
        'tramite': 'Inscripción y actualización de Abogado y Notario en el Registro Tributario Unificado (RTU)',
        'descripcion': 'Registra tu calidad profesional como Abogado y Notario en el RTU Digital presentando constancia de colegiado activo del CANG para habilitar gestiones notariales ante la SAT.',
        'baseLegal': 'Código de Notariado (Decreto 314, Art. 2), Ley de Colegiación Profesional Obligatoria (Decreto 72-2001) y Código Tributario (Art. 120).',
        'etapaAto': 'empezar',
        'etapaAtoLabel': 'Empezar y registrarse',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-71': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Traspaso Electrónico Vehicular (e-Traspaso)',
        'tema': 'Mandatos y Autorizaciones Vehiculares',
        'subtema': 'Legalización de Tercera Persona',
        'tramite': 'Autorización notarial de tercera persona en el Registro Fiscal de Vehículos',
        'descripcion': 'Elabora el acta notarial de legalización de firmas para facultar a un tercero o mandatario a realizar trámites y gestiones presenciales ante el Registro Fiscal de Vehículos.',
        'baseLegal': 'Código de Notariado (Decreto 314, Art. 54) y Ley del Impuesto sobre Circulación de Vehículos (Decreto 70-94).',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-32': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Traspaso Electrónico Vehicular (e-Traspaso)',
        'tema': 'Compraventa y Enajenación Vehicular',
        'subtema': 'Traspaso en Línea por Notario',
        'tramite': 'Formalización notarial de traspaso electrónico de vehículos en línea',
        'descripcion': 'Formaliza y autoriza electrónicamente la transferencia de dominio vehicular desde Agencia Virtual, validando el consentimiento de comprador y vendedor sin acudir a agencias.',
        'baseLegal': 'Ley del ISCV (Decreto 70-94, Art. 57) y Resoluciones de Directorio SAT para el Sistema e-Traspaso.',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-56': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Traspaso Electrónico Vehicular (e-Traspaso)',
        'tema': 'Expedientes Digitales TEV',
        'subtema': 'Firma Electrónica Avanzada',
        'tramite': 'Carga y remisión de expedientes digitales de traspaso con firma avanzada',
        'descripcion': 'Carga los testimonios y documentos digitalizados del traspaso vehicular firmados con Firma Electrónica Avanzada (FEA) para completar la validación jurídica registral.',
        'baseLegal': 'Ley para el Reconocimiento de las Comunicaciones y Firmas Electrónicas (Decreto 47-2008) y Ley del ISCV (Decreto 70-94).',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-33': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Avisos Notariales y Fe Pública',
        'tema': 'Control de Avisos Electrónicos',
        'subtema': 'Consulta de Estado y Constancias',
        'tramite': 'Consulta de avisos notariales y estado de legalizaciones registradas',
        'descripcion': 'Consulta en tiempo real el estado, recepción y aprobación de los avisos de transferencia vehicular y legalización de firmas transmitidos a través de la Agencia Virtual.',
        'baseLegal': 'Código de Notariado (Decreto 314, Art. 38) y Código Tributario (Decreto 6-91, Art. 112).',
        'etapaAto': 'consultar',
        'etapaAtoLabel': 'Consultas y herramientas',
        'tipoInteraccion': 'consulta_datos',
        'tipoInteraccionLabel': 'Consulta en Base de Datos',
        'tipologiaContenido': 'consulta_buscador',
        'tipologiaContenidoLabel': 'Buscador / Base de Datos',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-34': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Avisos Notariales y Fe Pública',
        'tema': 'Plazos y Calendario de Obligaciones',
        'subtema': 'Cumplimiento Legal Notarial',
        'tramite': 'Calendario y plazos de obligaciones notariales ante la SAT',
        'descripcion': 'Revisa el calendario oficial de plazos legales para la remisión de avisos notariales de traspaso y testimonios especiales afectos, evitando multas e inhabilitaciones.',
        'baseLegal': 'Código de Notariado (Decreto 314, Arts. 38 y 101) y Código Tributario (Decreto 6-91, Art. 94).',
        'etapaAto': 'normativa',
        'etapaAtoLabel': 'Normativa y asistencia',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-77': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Habilitación y Registro Notarial',
        'tema': 'Registro Tributario Unificado (RTU)',
        'subtema': 'Ratificación Anual de Notarios',
        'tramite': 'Ratificación anual de datos de Abogado y Notario en el Registro Tributario Unificado (RTU) Digital',
        'descripcion': 'Ratifica anualmente tus datos de bufete, domicilio fiscal y colegiado activo en el RTU Digital para conservar la habilitación en e-traspasos y compra de timbres.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Art. 120) y Acuerdo de Directorio SAT 08-2020.',
        'etapaAto': 'modificar_cerrar',
        'etapaAtoLabel': 'Modificaciones y cierre',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-66': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Timbres Fiscales y Papel Sellado de Protocolo',
        'tema': 'Compra de Especies Fiscales',
        'subtema': 'Formulario SAT-7130 Declaraguate',
        'tramite': 'Adquisición de Papel Sellado Especial para Protocolos y Timbres Fiscales (Formulario SAT-7130)',
        'descripcion': 'Genera tu formulario SAT-7130 en Declaraguate para adquirir hojas de papel sellado especial para protocolos (lotes de 50) y timbres fiscales para el ejercicio notarial.',
        'baseLegal': 'Decreto 37-92 (Ley del Impuesto de Timbres Fiscales y de Papel Sellado Especial para Protocolos, Arts. 23 al 27).',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'declaraguate',
        'plataformaSistemaLabel': 'Declaraguate',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-67': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Habilitación y Registro Notarial',
        'tema': 'Agencia Virtual Profesional',
        'subtema': 'Activación del Rol Notario',
        'tramite': 'Activación de calidad de Abogado y Notario en Agencia Virtual',
        'descripcion': 'Activa tu perfil especializado de Abogado y Notario en la Agencia Virtual para habilitar los módulos de e-traspaso vehicular, razón electrónica y avisos notariales.',
        'baseLegal': 'Código de Notariado (Decreto 314, Art. 2) y Acuerdos de Directorio SAT para el Sistema de Agencia Virtual.',
        'etapaAto': 'empezar',
        'etapaAtoLabel': 'Empezar y registrarse',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-68': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Habilitación y Registro Notarial',
        'tema': 'Seguridad Biométrica Notarial',
        'subtema': 'Registro de Huella Dactilar',
        'tramite': 'Registro y confirmación de huella dactilar biométrica',
        'descripcion': 'Registra tu impresión dactilar biométrica en agencias tributarias como mecanismo de autenticación de máxima seguridad para autorizar traspasos y contratos vehiculares.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Art. 112) y Resoluciones de Seguridad Tecnológica y Biométrica de la SAT.',
        'etapaAto': 'empezar',
        'etapaAtoLabel': 'Empezar y registrarse',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Presencial / Agencia',
        'esBrecha': False
    },
    'profesionales-72': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Avisos Notariales y Fe Pública',
        'tema': 'Avisos de Vehículos Terrestres',
        'subtema': 'Legalización de Firmas en Título',
        'tramite': 'Aviso notarial de legalización de firmas en título de propiedad vehicular',
        'descripcion': 'Transmite electrónicamente a la SAT el aviso de legalización de firmas efectuado en el certificado de propiedad de vehículos dentro del plazo de 15 días hábiles.',
        'baseLegal': 'Ley del Impuesto sobre Circulación de Vehículos (Decreto 70-94, Art. 57) y Código de Notariado (Art. 54).',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-73': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Avisos Notariales y Fe Pública',
        'tema': 'Avisos de Vehículos Terrestres',
        'subtema': 'Transferencia de Dominio',
        'tramite': 'Aviso notarial de transferencia de dominio de vehículos terrestres',
        'descripcion': 'Notifica a la administración tributaria la enajenación formal de automotores autorizada en escritura pública para actualizar el registro del vendedor y comprador.',
        'baseLegal': 'Ley del ISCV (Decreto 70-94, Art. 57) y Código de Notariado (Decreto 314, Art. 38).',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-74': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Traspaso Electrónico Vehicular (e-Traspaso)',
        'tema': 'Habilitación de Notarios en TEV',
        'subtema': 'Convenio y Contrato de Adhesión',
        'tramite': 'Habilitación de Notario para Traspaso Electrónico de Vehículos (TEV)',
        'descripcion': 'Suscribe el convenio de adhesión y habilita tu usuario notarial para operar el sistema TEV con firma electrónica avanzada y validación biométrica.',
        'baseLegal': 'Ley del ISCV (Decreto 70-94) y Acuerdo de Directorio SAT de Implementación del Sistema TEV.',
        'etapaAto': 'empezar',
        'etapaAtoLabel': 'Empezar y registrarse',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-75': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Avisos Notariales y Fe Pública',
        'tema': 'Atención Preferencial Notarial',
        'subtema': 'Ventanillas Exclusivas en Agencias',
        'tramite': 'Atención preferencial y requisitos en ventanillas notariales',
        'descripcion': 'Conoce los requisitos de acreditación (carné CANG activo y sello) para acceder a ventanillas preferenciales de atención notarial en agencias tributarias del país.',
        'baseLegal': 'Código de Notariado (Decreto 314) y Manual de Atención al Contribuyente de la SAT.',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Presencial / Agencia',
        'esBrecha': False
    },
    'profesionales-21': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Timbres Fiscales y Papel Sellado de Protocolo',
        'tema': 'Razón Electrónica de Timbres',
        'subtema': 'Pago y Emisión en Agencia Virtual',
        'tramite': 'Pago del Impuesto de Timbres Fiscales en línea con razón electrónica',
        'descripcion': 'Liquida el Impuesto de Timbres Fiscales mediante Declaraguate y genera la razón electrónica con código QR para adherir a testimonios de escrituras públicas.',
        'baseLegal': 'Decreto 37-92 (Ley del Impuesto de Timbres Fiscales y de Papel Sellado Especial para Protocolos, Arts. 16 al 22).',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-timbres-devolucion-papel-sellado': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Timbres Fiscales y Papel Sellado de Protocolo',
        'tema': 'Devolución y Canje de Especies',
        'subtema': 'Papel Inutilizado o Deteriorado',
        'tramite': 'Devolución y canje de timbres fiscales y papel sellado inutilizado',
        'descripcion': 'Solicita la reposición física o reintegro dinerario por hojas de papel de protocolo o timbres fiscales inutilizados, deteriorados o con errores de impresión.',
        'baseLegal': 'Decreto 37-92 (Ley del Impuesto de Timbres Fiscales y de Papel Sellado Especial para Protocolos, Arts. 29 al 32).',
        'etapaAto': 'modificar_cerrar',
        'etapaAtoLabel': 'Modificaciones y cierre',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Presencial / Agencia',
        'esBrecha': False
    },
    'profesionales-capacitacion-timbres-notarios': {
        'categoria': 'Abogados y Notarios',
        'subcategoria': 'Timbres Fiscales y Papel Sellado de Protocolo',
        'tema': 'Capacitación Especializada Notarial',
        'subtema': 'Cursos Virtuales de Especies Fiscales',
        'tramite': 'Capacitación sobre emisión de razón electrónica de timbres notariales',
        'descripcion': 'Accede al curso virtual interactivo sobre cálculo de tarifas, emisión de boletas y generación de razones electrónicas de timbres fiscales para el ejercicio notarial.',
        'baseLegal': 'Decreto 37-92 (Ley de Timbres Fiscales) y Plan de Formación Tributaria de la SAT.',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'recurso_descargable',
        'tipologiaContenidoLabel': 'Recurso / Formulario Descargable',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },

    # =========================================================================
    # 2. PERITOS CONTADORES (11 TRÁMITES)
    # =========================================================================
    'profesionales-82': {
        'categoria': 'Peritos Contadores',
        'subcategoria': 'Habilitación y Registro de Perito Contador',
        'tema': 'Registro de Contadores ante SAT',
        'subtema': 'Inscripción Inicial de Contador',
        'tramite': 'Inscripción y habilitación como Perito Contador ante la SAT',
        'descripcion': 'Inscribe tu título oficial de Perito Contador ante la SAT presentando título registrado en Contraloría General de Cuentas para quedar facultado para firmar contabilidades.',
        'baseLegal': 'Decreto 2450 (Normas que Regulan el Ejercicio de la Profesión de Contador) y Código Tributario (Art. 120).',
        'etapaAto': 'empezar',
        'etapaAtoLabel': 'Empezar y registrarse',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Presencial / Agencia',
        'esBrecha': False
    },
    'profesionales-80': {
        'categoria': 'Peritos Contadores',
        'subcategoria': 'Habilitación y Registro de Perito Contador',
        'tema': 'Registro de Contadores ante SAT',
        'subtema': 'Actualización Registral en Agencia Virtual',
        'tramite': 'Actualización de datos de Perito Contador en Agencia Virtual',
        'descripcion': 'Actualiza periódicamente tu información de contacto, domicilio fiscal y estado en el Registro de Contadores para mantener vigente tu firma técnica autorizada.',
        'baseLegal': 'Decreto 2450 (Normas de la Profesión Contable) y Código Tributario (Decreto 6-91, Art. 120).',
        'etapaAto': 'modificar_cerrar',
        'etapaAtoLabel': 'Modificaciones y cierre',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-81': {
        'categoria': 'Peritos Contadores',
        'subcategoria': 'Habilitación y Registro de Perito Contador',
        'tema': 'Cese y Desvinculación Contable',
        'subtema': 'Aviso de Baja en Agencia Virtual',
        'tramite': 'Cancelación y baja como Contador en Agencia Virtual',
        'descripcion': 'Presenta el aviso formal de baja en el Registro de Contadores o desvinculación de las contabilidades que tengas asignadas para cesar tu responsabilidad técnica.',
        'baseLegal': 'Decreto 2450 (Normas de la Profesión Contable) y Código Tributario (Decreto 6-91, Arts. 23 y 120).',
        'etapaAto': 'modificar_cerrar',
        'etapaAtoLabel': 'Modificaciones y cierre',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-83': {
        'categoria': 'Peritos Contadores',
        'subcategoria': 'Habilitación y Registro de Perito Contador',
        'tema': 'Agencia Virtual Profesional',
        'subtema': 'Activación de Cuenta de Contador',
        'tramite': 'Registro y habilitación de Contador en Agencia Virtual',
        'descripcion': 'Habilita tu usuario y rol de Perito Contador en la Agencia Virtual para aceptar asignaciones de clientes y administrar libros contables digitales.',
        'baseLegal': 'Decreto 2450 (Normas de la Profesión Contable) y Resoluciones de Agencia Virtual SAT.',
        'etapaAto': 'empezar',
        'etapaAtoLabel': 'Empezar y registrarse',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-16': {
        'categoria': 'Peritos Contadores',
        'subcategoria': 'Consultas, Retenciones y Libros Contables',
        'tema': 'Retenciones Tributarias',
        'subtema': 'Consulta de Constancias IVA e ISR',
        'tramite': 'Consulta en línea de constancias de retención del Impuesto al Valor Agregado (IVA) e Impuesto Sobre la Renta (ISR)',
        'descripcion': 'Consulta y concilia en tiempo real las constancias de retención de IVA e ISR emitidas a favor de tus clientes para aplicarlas en las declaraciones mensuales.',
        'baseLegal': 'Ley del IVA (Decreto 27-92, Art. 47 bis) y Ley de Actualización Tributaria (Decreto 10-2012, Art. 86).',
        'etapaAto': 'consultar',
        'etapaAtoLabel': 'Consultas y herramientas',
        'tipoInteraccion': 'consulta_datos',
        'tipoInteraccionLabel': 'Consulta en Base de Datos',
        'tipologiaContenido': 'consulta_buscador',
        'tipologiaContenidoLabel': 'Buscador / Base de Datos',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-17': {
        'categoria': 'Peritos Contadores',
        'subcategoria': 'Consultas, Retenciones y Libros Contables',
        'tema': 'Facturación Electrónica en Línea (FEL)',
        'subtema': 'Administración y Conciliación DTE',
        'tramite': 'Guía y administración del régimen de Factura Electrónica en Línea (FEL)',
        'descripcion': 'Administra la emisión masiva, anulación y reporte de Documentos Tributarios Electrónicos (DTE) de tus clientes mediante la Agencia Virtual o certificador.',
        'baseLegal': 'Ley del IVA (Decreto 27-92, Arts. 29 y 29 "A") y Acuerdo de Directorio SAT 13-2018.',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-18': {
        'categoria': 'Peritos Contadores',
        'subcategoria': 'Consultas, Retenciones y Libros Contables',
        'tema': 'Crédito Fiscal del IVA',
        'subtema': 'Planilla Electrónica IVA-FEL',
        'tramite': 'Presentación de Planilla del Impuesto al Valor Agregado (IVA) en Factura Electrónica en Línea (FEL)',
        'descripcion': 'Carga y transmite la planilla anual del IVA con facturas electrónicas para trabajadores asalariados de tus clientes para acreditar crédito fiscal contra el ISR.',
        'baseLegal': 'Ley de Actualización Tributaria (Decreto 10-2012, Art. 72) y Ley del IVA (Decreto 27-92, Art. 37).',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-19': {
        'categoria': 'Peritos Contadores',
        'subcategoria': 'Consultas, Retenciones y Libros Contables',
        'tema': 'Libros Contables Electrónicos',
        'subtema': 'Libro Electrónico Tributario (LET)',
        'tramite': 'Habilitación y administración del Libro Electrónico Tributario (LET)',
        'descripcion': 'Habilita y genera el Libro Electrónico Tributario (LET) para llevar el registro digital mensual de compras y ventas de pequeños contribuyentes y régimen general.',
        'baseLegal': 'Código de Comercio (Decreto 2-70, Arts. 368 al 371) y Acuerdo de Directorio SAT 08-2021 (Régimen LET).',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-42': {
        'categoria': 'Peritos Contadores',
        'subcategoria': 'Consultas, Retenciones y Libros Contables',
        'tema': 'Gestión de Créditos y Pagos Indebidos',
        'subtema': 'Devolución y Compensación Tributaria',
        'tramite': 'Solicitud de devolución, retención o compensación de créditos tributarios',
        'descripcion': 'Prepara y radica la solicitud formal para la devolución de pagos indebidos o compensación de saldos acreedores de impuestos internos conforme al Código Tributario.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Arts. 99 y 153) y Ley del IVA (Decreto 27-92, Art. 23).',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Presencial / Agencia',
        'esBrecha': False
    },
    'profesionales-44': {
        'categoria': 'Peritos Contadores',
        'subcategoria': 'Consultas, Retenciones y Libros Contables',
        'tema': 'Rectificaciones y Correcciones',
        'subtema': 'Autoliquidación y Omisos',
        'tramite': 'Procedimiento y rectificación para autoliquidación de impuestos',
        'descripcion': 'Aplica el procedimiento oficial para rectificar declaraciones juradas con error en Declaraguate, liquidando intereses resarcitorios y regularizando inconsistencias.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Arts. 106 y 110 - Rectificación de declaraciones).',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-46': {
        'categoria': 'Peritos Contadores',
        'subcategoria': 'Consultas, Retenciones y Libros Contables',
        'tema': 'Retenciones de IVA en Línea',
        'subtema': 'Sistema Retenciones Web IVA',
        'tramite': 'Operación y emisión en el Sistema de Retenciones del Impuesto al Valor Agregado (IVA)',
        'descripcion': 'Opera el aplicativo Retenciones Web IVA para emitir constancias oficiales de retención y generar el archivo de carga para Declaraguate como agente de retención.',
        'baseLegal': 'Ley del IVA (Decreto 27-92, Art. 47 bis) y Acuerdos de Agentes de Retención del IVA.',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },

    # =========================================================================
    # 3. AUDITORES — CONTADORES PÚBLICOS Y AUDITORES (4 TRÁMITES)
    # =========================================================================
    'profesionales-89': {
        'categoria': 'Auditores',
        'subcategoria': 'Dictámenes de Crédito Fiscal y Auditoría',
        'tema': 'Dictámenes de Crédito Fiscal',
        'subtema': 'Registro de CPA Dictaminador',
        'tramite': 'Inscripción de Contador autorizado para emitir dictámenes de devolución de crédito fiscal',
        'descripcion': 'Registra tu habilitación como Contador Público y Auditor ante la SAT para emitir dictámenes profesionales en solicitudes de devolución de crédito fiscal a exportadores.',
        'baseLegal': 'Ley del IVA (Decreto 27-92, Art. 25 bis) y Acuerdo de Directorio SAT 07-2007 (Régimen Optativo de Devolución).',
        'etapaAto': 'empezar',
        'etapaAtoLabel': 'Empezar y registrarse',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Presencial / Agencia',
        'esBrecha': False
    },
    'profesionales-91': {
        'categoria': 'Auditores',
        'subcategoria': 'Habilitación y Registro de Auditor (CPA)',
        'tema': 'Registro de Auditores ante SAT',
        'subtema': 'Inscripción de Colegiado CPA',
        'tramite': 'Inscripción y habilitación como Contador Público y Auditor (CPA)',
        'descripcion': 'Inscribe tu título profesional de Contador Público y Auditor (CPA) con constancia de colegiado activo del Colegio de CPA o Economistas para emitir informes técnicos.',
        'baseLegal': 'Ley de Colegiación Profesional Obligatoria (Decreto 72-2001) y Código Tributario (Art. 120).',
        'etapaAto': 'empezar',
        'etapaAtoLabel': 'Empezar y registrarse',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Presencial / Agencia',
        'esBrecha': False
    },
    'profesionales-88': {
        'categoria': 'Auditores',
        'subcategoria': 'Dictámenes de Crédito Fiscal y Auditoría',
        'tema': 'Dictámenes de Crédito Fiscal',
        'subtema': 'Actualización Anual de CPA Emisor',
        'tramite': 'Actualización de datos de Contador que emite dictámenes de devolución',
        'descripcion': 'Actualiza anualmente tu fianza y datos profesionales en el Registro de CPA Emisores de Dictámenes para continuar emitiendo dictámenes bajo el régimen optativo.',
        'baseLegal': 'Ley del IVA (Decreto 27-92, Art. 25 bis) y Acuerdo de Directorio SAT 07-2007.',
        'etapaAto': 'modificar_cerrar',
        'etapaAtoLabel': 'Modificaciones y cierre',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Presencial / Agencia',
        'esBrecha': False
    },
    'profesionales-90': {
        'categoria': 'Auditores',
        'subcategoria': 'Habilitación y Registro de Auditor (CPA)',
        'tema': 'Registro de Auditores ante SAT',
        'subtema': 'Actualización de Datos de Colegiado',
        'tramite': 'Actualización de datos de Contador Público y Auditor (CPA)',
        'descripcion': 'Actualiza tu número de colegiado activo, constancia de vigencia gremial y datos de contacto en el Registro de CPA de la SAT.',
        'baseLegal': 'Ley de Colegiación Profesional Obligatoria (Decreto 72-2001) y Código Tributario (Art. 120).',
        'etapaAto': 'modificar_cerrar',
        'etapaAtoLabel': 'Modificaciones y cierre',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Presencial / Agencia',
        'esBrecha': False
    },

    # =========================================================================
    # 4. GESTORES TRIBUTARIOS Y AUXILIARES (8 TRÁMITES)
    # =========================================================================
    'profesionales-54': {
        'categoria': 'Gestores Tributarios',
        'subcategoria': 'Acreditación y Carné Oficial de Gestor',
        'tema': 'Acreditación y Requisitos Institucionales',
        'subtema': 'Trámite Integral de Acreditación',
        'tramite': 'Acreditación integral, carné y renovación de Gestor Tributario y Auxiliares',
        'descripcion': 'Solicita la acreditación oficial, evaluación y expedición del carné institucional ante la SAT para actuar formalmente como gestor de trámites de terceros.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Art. 22 - Representación) y Manual Institucional de Acreditación de Gestores de la SAT.',
        'etapaAto': 'empezar',
        'etapaAtoLabel': 'Empezar y registrarse',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Presencial / Agencia',
        'esBrecha': False
    },
    'profesionales-59': {
        'categoria': 'Gestores Tributarios',
        'subcategoria': 'Renovación y Gestión de Gafetes',
        'tema': 'Control y Régimen Disciplinario',
        'subtema': 'Inhabilitación y Suspensión',
        'tramite': 'Habilitación e inhabilitación temporal o definitiva de Gestor Tributario o Auxiliar',
        'descripcion': 'Consulta las causales legales, sanciones y resoluciones de suspensión o inhabilitación temporal o definitiva en el ejercicio de gestiones ante oficinas tributarias.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Arts. 22 y 94) y Normativa de Control de Gestores Tributarios de la SAT.',
        'etapaAto': 'normativa',
        'etapaAtoLabel': 'Normativa y asistencia',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-30': {
        'categoria': 'Gestores Tributarios',
        'subcategoria': 'Acreditación y Carné Oficial de Gestor',
        'tema': 'Marco Legal y Alcance de Gestión',
        'subtema': 'Facultades y Trámites Permitidos',
        'tramite': 'Marco de actuación y alcance de los Gestores Tributarios acreditados',
        'descripcion': 'Conoce las gestiones autorizadas, límites de representación legal y responsabilidades de los gestores tributarios y auxiliares acreditados ante la SAT.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Art. 22) y Ley Orgánica de la SAT (Decreto 1-98).',
        'etapaAto': 'normativa',
        'etapaAtoLabel': 'Normativa y asistencia',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-41': {
        'categoria': 'Gestores Tributarios',
        'subcategoria': 'Acreditación y Carné Oficial de Gestor',
        'tema': 'Representación en RTU',
        'subtema': 'Autorización de Tercera Persona',
        'tramite': 'Acreditación de tercera persona autorizada para gestiones en el Registro Tributario Unificado (RTU)',
        'descripcion': 'Cumple los requisitos y presenta la carta poder o acta notarial para que una tercera persona autorizada ingrese trámites registrales del RTU en agencias.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Art. 22) y Acuerdo de Directorio SAT 08-2020.',
        'etapaAto': 'empezar',
        'etapaAtoLabel': 'Empezar y registrarse',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Presencial / Agencia',
        'esBrecha': False
    },
    'profesionales-58': {
        'categoria': 'Gestores Tributarios',
        'subcategoria': 'Renovación y Gestión de Gafetes',
        'tema': 'Verificación de Acreditación',
        'subtema': 'Consulta Pública de Padrón Activo',
        'tramite': 'Consulta en línea del padrón de Gestores Tributarios y Auxiliares activos',
        'descripcion': 'Verifica en tiempo real si un gestor o auxiliar tributario cuenta con carné vigente y habilitación activa para realizar trámites ante las dependencias de la SAT.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Art. 22) y Ley de Acceso a la Información Pública (Decreto 57-2008).',
        'etapaAto': 'consultar',
        'etapaAtoLabel': 'Consultas y herramientas',
        'tipoInteraccion': 'consulta_datos',
        'tipoInteraccionLabel': 'Consulta en Base de Datos',
        'tipologiaContenido': 'consulta_buscador',
        'tipologiaContenidoLabel': 'Buscador / Base de Datos',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-57': {
        'categoria': 'Gestores Tributarios',
        'subcategoria': 'Renovación y Gestión de Gafetes',
        'tema': 'Vigencia de Credencial',
        'subtema': 'Renovación Anual de Gafete',
        'tramite': 'Actualización de datos y renovación de gafete para Gestor Tributario',
        'descripcion': 'Presenta la solicitud anual de actualización de antecedentes penales, policiacos y solvencia fiscal para renovar la vigencia del gafete oficial de gestor.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Arts. 22 y 57 "A") y Normativa de Acreditación de Gestores de la SAT.',
        'etapaAto': 'modificar_cerrar',
        'etapaAtoLabel': 'Modificaciones y cierre',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Presencial / Agencia',
        'esBrecha': False
    },
    'profesionales-60': {
        'categoria': 'Gestores Tributarios',
        'subcategoria': 'Renovación y Gestión de Gafetes',
        'tema': 'Reposición de Credencial',
        'subtema': 'Extravío o Deterioro de Gafete',
        'tramite': 'Reposición de gafete de identificación para Gestor Tributario',
        'descripcion': 'Gestiona la reposición del gafete oficial por motivo de extravío, robo o deterioro físico adjuntando la denuncia respectiva y recibo de pago de reposición.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Art. 22) y Manual de Procedimientos Administrativos de la SAT.',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Presencial / Agencia',
        'esBrecha': False
    },
    'profesionales-61': {
        'categoria': 'Gestores Tributarios',
        'subcategoria': 'Acreditación y Carné Oficial de Gestor',
        'tema': 'Requisitos de Ingreso al Padrón',
        'subtema': 'Documentación Inicial y Examen',
        'tramite': 'Requisitos de acreditación inicial para Gestor Tributario o Auxiliar',
        'descripcion': 'Consulta los requisitos documentales (antecedentes, colegiado/estudios, solvencia) y fecha de evaluación técnica para acreditarte por primera vez ante la SAT.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Art. 22) y Manual de Acreditación de Gestores de la SAT.',
        'etapaAto': 'empezar',
        'etapaAtoLabel': 'Empezar y registrarse',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },

    # =========================================================================
    # 5. SERVICIOS PROFESIONALES GENERALES (6 TRÁMITES)
    # =========================================================================
    'profesionales-78': {
        'categoria': 'Servicios Profesionales',
        'subcategoria': 'Sistemas de Retención y Cumplimiento',
        'tema': 'Cumplimiento Voluntario',
        'subtema': 'Programa y Herramientas Tributarias',
        'tramite': 'Documentación y herramientas del Programa de Cumplimiento Tributario Voluntario',
        'descripcion': 'Accede a las guías metodológicas y herramientas de autoevaluación fiscal del Programa de Cumplimiento Voluntario de la SAT para mitigar riesgos de auditoría.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Art. 112) y Ley Orgánica de la SAT (Decreto 1-98).',
        'etapaAto': 'normativa',
        'etapaAtoLabel': 'Normativa y asistencia',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'recurso_descargable',
        'tipologiaContenidoLabel': 'Recurso / Formulario Descargable',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-20': {
        'categoria': 'Servicios Profesionales',
        'subcategoria': 'Facturación por Honorarios y Formularios',
        'tema': 'Formularios Tributarios Oficiales',
        'subtema': 'Declaraguate Catálogo Completo',
        'tramite': 'Catálogo general de formularios tributarios electrónicos en Declaraguate',
        'descripcion': 'Consulta y genera todos los formularios electrónicos para la liquidación mensual, trimestral y anual de impuestos por honorarios y servicios técnicos.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Art. 106) y Ley de Actualización Tributaria (Decreto 10-2012, Libro I).',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'declaraguate',
        'plataformaSistemaLabel': 'Declaraguate',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-29': {
        'categoria': 'Servicios Profesionales',
        'subcategoria': 'Actualización de Actividad y RTU',
        'tema': 'Registro Tributario Unificado (RTU)',
        'subtema': 'Actualización de Actividad Profesional',
        'tramite': 'Actualización de datos registrales de Servicios Profesionales en Agencia Virtual',
        'descripcion': 'Modifica o ratifica en el RTU Digital tus actividades económicas profesionales, régimen de afiliación (IVA/ISR) y datos de domicilio fiscal o clínica/oficina.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Art. 120) y Acuerdo de Directorio SAT 08-2020.',
        'etapaAto': 'modificar_cerrar',
        'etapaAtoLabel': 'Modificaciones y cierre',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'agencia_virtual',
        'plataformaSistemaLabel': 'Agencia Virtual SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-4': {
        'categoria': 'Servicios Profesionales',
        'subcategoria': 'Consultas Jurídico Tributarias',
        'tema': 'Consultas Técnicas Vinculantes',
        'subtema': 'Asuntos Jurídicos SAT',
        'tramite': 'Presentación de consultas técnico-tributarias vinculantes ante Asuntos Jurídicos',
        'descripcion': 'Presenta consultas técnico-jurídicas formales sobre la aplicación de normas tributarias ante la Intendencia de Asuntos Jurídicos para obtener criterio vinculante.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Arts. 102 al 105 - Consultas vinculantes).',
        'etapaAto': 'consultar',
        'etapaAtoLabel': 'Consultas y herramientas',
        'tipoInteraccion': 'guia_informativa',
        'tipoInteraccionLabel': 'Guía Informativa / Texto',
        'tipologiaContenido': 'guia_requisitos',
        'tipologiaContenidoLabel': 'Guía Informativa / Texto',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Presencial / Agencia',
        'esBrecha': False
    },
    'profesionales-45': {
        'categoria': 'Servicios Profesionales',
        'subcategoria': 'Sistemas de Retención y Cumplimiento',
        'tema': 'Retenciones Sector Salud',
        'subtema': 'Asiste Hospitales Web',
        'tramite': 'Sistema de retenciones para servicios médicos y hospitalarios (Asiste Web)',
        'descripcion': 'Opera el aplicativo Asiste Hospitales Web para gestionar y conciliar retenciones del ISR aplicables a servicios prestados por médicos en clínicas y sanatorios.',
        'baseLegal': 'Ley de Actualización Tributaria (Decreto 10-2012, Arts. 84 al 86) y Resoluciones de Retenciones SAT.',
        'etapaAto': 'operar',
        'etapaAtoLabel': 'Operación y declaraciones',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    },
    'profesionales-objeciones-asuntos-juridicos': {
        'categoria': 'Servicios Profesionales',
        'subcategoria': 'Consultas Jurídico Tributarias',
        'tema': 'Criterios y Doctrina Tributaria',
        'subtema': 'Objeciones a Procedimientos SAT',
        'tramite': 'Recepción de propuestas y observaciones técnicas a criterios de Asuntos Jurídicos',
        'descripcion': 'Envía observaciones técnicas, sugerencias o cuestionamientos fundamentados a los proyectos de criterios institucionales publicados por la Intendencia de Asuntos Jurídicos.',
        'baseLegal': 'Código Tributario (Decreto 6-91, Art. 112) y Ley Orgánica de la SAT (Decreto 1-98, Art. 3).',
        'etapaAto': 'normativa',
        'etapaAtoLabel': 'Normativa y asistencia',
        'tipoInteraccion': 'servicio_transaccional',
        'tipoInteraccionLabel': 'Trámite / Aplicativo en Línea',
        'tipologiaContenido': 'tramite_interactivo',
        'tipologiaContenidoLabel': 'Trámite en Línea Interactivo',
        'plataformaSistema': 'portal_web',
        'plataformaSistemaLabel': 'Portal Web SAT',
        'canalAtencion': 'Digital / Web',
        'esBrecha': False
    }
}

# Aplicar las correcciones a allTramites.json
updated_count = 0
for t in data:
    tid = t.get('id')
    if tid in PROFESIONALES_AUDIT:
        audit = PROFESIONALES_AUDIT[tid]
        
        t['categoria'] = audit['categoria']
        t['subcategoria'] = audit['subcategoria']
        t['tema'] = audit['tema']
        t['subtema'] = audit['subtema']
        t['tramite'] = audit['tramite']
        t['descripcion'] = audit['descripcion']
        t['baseLegal'] = audit['baseLegal']
        t['etapaAto'] = audit['etapaAto']
        t['etapaAtoLabel'] = audit['etapaAtoLabel']
        t['tipoInteraccion'] = audit['tipoInteraccion']
        t['tipoInteraccionLabel'] = audit['tipoInteraccionLabel']
        t['tipologiaContenido'] = audit['tipologiaContenido']
        t['tipologiaContenidoLabel'] = audit['tipologiaContenidoLabel']
        t['plataformaSistema'] = audit['plataformaSistema']
        t['plataformaSistemaLabel'] = audit['plataformaSistemaLabel']
        t['canalAtencion'] = audit['canalAtencion']
        t['esBrecha'] = audit['esBrecha']
        
        # Jerarquía N1 a N5 completa y estructurada
        cat = audit['categoria']
        subcat = audit['subcategoria']
        tema = audit['tema']
        subtema = audit['subtema']
        tr = audit['tramite']
        
        t['nivel1_segmento'] = 'Profesionales'
        t['nivel2_area'] = cat
        t['nivel3_subarea'] = subcat
        t['nivel4_tema'] = tema
        t['nivel5_tramite'] = subtema
        t['migaBreadcrumb'] = f"Profesionales > {cat} > {subcat} > {tr}"
        t['controlAuditoria'] = 'APROBADO'
        t['segmento'] = 'Profesionales'
        t['regimenArea'] = 'Servicios Profesionales y Terceras Personas'
        t['grupoActor'] = cat
        
        updated_count += 1

print(f"Total trámites de profesionales actualizados con IA completa: {updated_count} de 47")

with open(ALL_TRAMITES_PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Dataset maestro {ALL_TRAMITES_PATH} guardado con éxito.")
